import {
  Activity, AtSign, BadgeAlert, BadgeInfo, Ban, BookUser, Bookmark, BookmarkCheck, BookmarkMinus,
  BookmarkOff, BookmarkPlus, BookmarkX, CircleUser, CircleUserRound, Cog, Contact, ContactRound, CreditCard, FileUser, FingerprintPattern,
  Flag, FlagOff, Gift, HeartPlus, HeartMinus, IdCard, IdCardLanyard, Inbox, Key, KeyRound, KeySquare, NotebookTabs, RotateCcwKeyIcon,
  ScanEye, ScanFace, ScanQrCode, Settings, Settings2, Shield, ShieldAlert, ShieldBan, ShieldCheck, ShieldCog, ShieldCogCorner, ShieldEllipsis,
  ShieldHalf, ShieldPlus, ShieldQuestionMark, ShieldUser, ShieldX, SquareUser, SquareUserRound, Star, Tags, ThumbsUp, ThumbsDown, User,
  UserCheck, UserCog, UserLock, UserRound, UserRoundCog, Wallet, WalletCards, WalletMinimal, Waypoints, Webhook, WebhookOff, Wrench, WrenchOff,
  type LucideIcon, HelpCircle
} from 'lucide-react';

export const IconMap: Record<string, LucideIcon> = {
  'activity': Activity,
  'at-sign': AtSign,
  'badge-alert': BadgeAlert,
  'badge-info': BadgeInfo,
  'ban': Ban,
  'book-user': BookUser,
  'bookmark': Bookmark,
  'bookmark-check': BookmarkCheck,
  'bookmark-minus': BookmarkMinus,
  'bookmark-off': BookmarkOff,
  'bookmark-plus': BookmarkPlus,
  'bookmark-x': BookmarkX,
  'circle-user': CircleUser,
  'circle-user-round': CircleUserRound,
  'cog': Cog,
  'contact': Contact,
  'contact-round': ContactRound,
  'credit-card': CreditCard,
  'file-user': FileUser,
  'fingerprint-pattern': FingerprintPattern,
  'flag': Flag,
  'flag-off': FlagOff,
  'gift': Gift,
  'heart-plus': HeartPlus,
  'heart-minus': HeartMinus,
  'id-card': IdCard,
  'id-card-lanyard': IdCardLanyard,
  'inbox': Inbox,
  'key': Key,
  'key-round': KeyRound,
  'key-square': KeySquare,
  'notebook-tabs': NotebookTabs,
  'rotate-ccw-key-icon': RotateCcwKeyIcon,
  'scan-eye': ScanEye,
  'scan-face': ScanFace,
  'scan-qr-code': ScanQrCode,
  'settings': Settings,
  'settings-2': Settings2,
  'shield': Shield,
  'shield-alert': ShieldAlert,
  'shield-ban': ShieldBan,
  'shield-check': ShieldCheck,
  'shield-cog': ShieldCog,
  'shield-cog-corner': ShieldCogCorner,
  'shield-ellipsis': ShieldEllipsis,
  'shield-half': ShieldHalf,
  'shield-plus': ShieldPlus,
  'shield-question-mark': ShieldQuestionMark,
  'shield-user': ShieldUser,
  'shield-x': ShieldX,
  'square-user': SquareUser,
  'square-user-round': SquareUserRound,
  'star': Star,
  'tags': Tags,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'user': User,
  'user-check': UserCheck,
  'user-cog': UserCog,
  'user-lock': UserLock,
  'user-round': UserRound,
  'user-round-cog': UserRoundCog,
  'wallet': Wallet,
  'wallet-cards': WalletCards,
  'wallet-minimal': WalletMinimal,
  'waypoints': Waypoints,
  'webhook': Webhook,
  'webhook-off': WebhookOff,
  'wrench': Wrench,
  'wrench-off': WrenchOff
};

export const RenderIcon = ({ name, size = 24, color = "text-white", className = "" }: { name: string, size?: number, color: string, className?: string }) => {
  const Icon = IconMap[name] || HelpCircle;
  return <Icon size={size} color={color} className={className} />;
};
